### ISSUE TITLE
when the photo is *.bmp,  the LCD couldn't show correctly.

### ISSUE THREAD

**Issue by prife** [RT-Thread/realboard-stm32f4#1]
It seems sometimes, the content in the buffer after reading  a line,  some bytes are dislocated.

数码相框的例子中，当图片格式是bmp时，显示图像有误，经过调试后发现，某些内容会发送错位，导致RGB次序混乱。原因可能处在数码相框的代码也可能是fatfs有bug，但是下面这个函数却总可以正确显示分辨率为800×480，格式为24位真彩的BMP图像。

所以真的很奇怪...

while the following code can show bmp (24bit format, 800*480) correctly..
# define HEAD_SIZE 54

unsigned char mybuf[3*800];

void dispic(char \* file)
{
    int fd;
    int offset, i, j;
    unsigned char b, g, r;
    unsigned short color;
    unsigned char \* checkbuf = mybuf;
    fd = open(file, O_RDONLY, 0);
    if (fd < 0)
        rt_kprintf("open file <%s> error!\n", file);

```
offset = HEAD_SIZE + 800*480*3;

for(i=0; i<480; i++)
{
    offset -= 800*3;
    lseek(fd, offset, DFS_SEEK_SET);
    memset(checkbuf, 0, sizeof(mybuf));
    if (read(fd, checkbuf, sizeof(mybuf)) < 0)
    {
        rt_kprintf("read error, offset = %d\n", offset);
        goto __ret;
    }
    for (j=0; j<800; j++)
    {
        b = checkbuf[j*3+0];
        g = checkbuf[j*3+1];
        r = checkbuf[j*3+2]; 
        color = 0;            
        color |= ( (((unsigned)r)<<8) & 0xF800);
        color |= ( (((unsigned)g)<<3) & 0x07e0);
        color |= ( (((unsigned)b)>>3) );        
        //check
        XY_Coordinate(j, i);
        LCD_CmdWrite(0x02);//set CMD02 to  prepare data write
        LCD_DataWrite(color);  //write red data
    }
}
```

__ret:
    return;
}
# include "finsh.h"

FINSH_FUNCTION_EXPORT(dispic, xxxxx)

**Comment by grissiom** [comment]
貌似最后定位到文件系统或SD驱动里了？如果要是这样的话等这个 bug 解掉之后我再更新 svn 里的 RTGUI 吧，里面有 onelife 优化过的 bmp engine ;)

**Comment by BernardXiong** [comment]
onelife的bmp engine还未更新进来吗？可以考虑跟进了。realtouch上的AppMgr估计我得等到下周才有时间。

**Comment by grissiom** [comment]
onelife 的 bmp engine 在 github 的 RTGUI 里，但是 RTGUI 还没有同步到 svn……

我在本地已经做好同步的准备了，MDK，GCC 编译起来没问题～ 但是如果现在同步过去，bmp 或许会有新的 bug，几个 bug 摞一起 @prife 会不会不好解？……

**Comment by prife** [comment]
这个问题处在SD卡驱上的概率很大，因为我将数码相框的程序在2440+qemu上跑了一下，没有任何问题。

而在realtouch上，只要给read 传入的buffer地址是对齐的
，read读到的buffer内容中，中间部分数据就会发送一个字节的错位。导致最后显示的图像大量条纹。这个bug与UI无关。可以推送。

感觉SD卡驱动的概率要大一些。先查这个。这个要aozima来搞了。

在 2012年7月20日 上午11:07，Grissiom.GuRui <
reply@reply.github.com

> 写道：
> 
> onelife 的 bmp engine 在 github 的 RTGUI 里，但是 RTGUI 还没有同步到 svn……
> 
> 我在本地已经做好同步的准备了，MDK，GCC 编译起来没问题～ 但是如果现在同步过去，bmp 或许会有新的 bug，几个 bug 摞一起
> @prife 会不会不好解？……
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/RT-Thread/realtouch-stm32f4/issues/1#issuecomment-7121308

## 

把有限的时间投入到无限的学习中去

**Comment by prife** [comment]
grissiom将BMP 引擎commit到svn上即可，没有问题。

在 2012年7月20日 上午11:20，prife goprife@gmail.com写道：

> 这个问题处在SD卡驱上的概率很大，因为我将数码相框的程序在2440+qemu上跑了一下，没有任何问题。
> 
> 而在realtouch上，只要给read 传入的buffer地址是对齐的
> ，read读到的buffer内容中，中间部分数据就会发送一个字节的错位。导致最后显示的图像大量条纹。这个bug与UI无关。可以推送。
> 
> 感觉SD卡驱动的概率要大一些。先查这个。这个要aozima来搞了。
> 
> 在 2012年7月20日 上午11:07，Grissiom.GuRui <
> reply@reply.github.com
> 
> > 写道：
> 
> onelife 的 bmp engine 在 github 的 RTGUI 里，但是 RTGUI 还没有同步到 svn……
> 
> > 我在本地已经做好同步的准备了，MDK，GCC 编译起来没问题～ 但是如果现在同步过去，bmp 或许会有新的 bug，几个 bug 摞一起
> > @prife 会不会不好解？……
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/RT-Thread/realtouch-stm32f4/issues/1#issuecomment-7121308
> 
> ## 
> 
> 把有限的时间投入到无限的学习中去

## 

把有限的时间投入到无限的学习中去

**Comment by yqiu2018** [comment]
我之前试过显示 PNG 图片，貌似也有问题；

**Comment by prife** [comment]
fixed by commit d4901f0f7f
