### ISSUE TITLE
build error with realtouch 290 + rtthread 2581 

### ISSUE THREAD

**Issue by wnnwoo** [RT-Thread/realboard-stm32f4#13]
The latest realtouch(revision 290) is not compatible with the latest rt-thread(revision 2581),  here is the build error:

Build target 'RTThread'
compiling ra8875.c...
drivers\ra8875.c(755): error:  #70: incomplete type is not allowed
drivers\ra8875.c(826): error:  #20: identifier "RTGUI_CURSOR_ARROW" is undefined
drivers\ra8875.c(32): warning:  #177-D: function "_wait_lcd_ready" was declared but never referenced
drivers\ra8875.c(67): warning:  #177-D: function "LCD_read_reg" was declared but never referenced
drivers\ra8875.c(258): warning:  #177-D: function "_set_draw_point2_cursor" was declared but never referenced
compiling appmgr.c...
ui\appmgr.c(70): warning:  #223-D: function "program_create" declared implicitly
ui\appmgr.c(99): error:  #167: argument of type "char *" is incompatible with parameter of type "rt_thread_t"
ui\appmgr.c(99): error:  #165: too few arguments in function call
ui\appmgr.c(103): error:  #140: too many arguments in function call
compiling calibration.c...
ui\calibration.c(258): error:  #167: argument of type "char *" is incompatible with parameter of type "rt_thread_t"
ui\calibration.c(258): error:  #165: too few arguments in function call

**Comment by BernardXiong** [comment]
please use newest RT-Thread GUI to compile firmware.
