### ISSUE TITLE
realtouch link fails with the newest RTGUI

### ISSUE THREAD

**Issue by prife** [RT-Thread/realboard-stm32f4#14]
`F:\Project\git\realtouch-stm32f4\software\realtouch>scons -j4`
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: build
LINK rtthread-stm32f4xx.axf
Error: L6200E: Symbol __fsym_calibration_name multiply defined (by calibration.o
 and calibration.o).
Error: L6200E: Symbol __fsym_calibration_desc multiply defined (by calibration.o
 and calibration.o).
Error: L6200E: Symbol calibration_init multiply defined (by calibration.o and ca
libration.o).
Error: L6200E: Symbol calibration multiply defined (by calibration.o and calibra
tion.o).
Error: L6200E: Symbol __fsym_calibration multiply defined (by calibration.o and
calibration.o).
Finished: 0 information, 0 warning and 5 error messages.
scons: **\* [rtthread-stm32f4xx.axf] Error 1
scons: building terminated because of errors.

**Comment by grissiom** [comment]
Is your working copy fully updated? There is no calibration.c in realtouch now...

**Comment by prife** [comment]
While, the following file still exists in realtouch.
https://github.com/RT-Thread/realtouch-stm32f4/blob/master/software/realtouch/ui/calibration.c

2013/3/21 Grissiom.GuRui notifications@github.com

> Is your working copy fully updated? There is no calibration.c in realtouch
> now...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/RT-Thread/realtouch-stm32f4/issues/14#issuecomment-15224827
> .

## 

把有限的时间投入到无限的学习中去

**Comment by grissiom** [comment]
Oops, sorry that I forgot to commit the files. Please try again ;)
