### ISSUE TITLE
compile errors in drivers/stm32f4xx_it.c

### ISSUE THREAD

**Issue by prife** [RT-Thread/realboard-stm32f4#2]
使用gcc编译时：

realtouch-stm32f4/software/examples/drivers/stm32f4xx_it.c:201:8: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'void'

201 __weak void key_handler(void)
202 {
203     /\* do nothing. */
204 }

**Comment by prife** [comment]
#if defined(**CC_ARM)
__weak void key_handler(void)
#elif defined(__GNUC**)
void  key_handler(void) **attribute** ((weak));
void key_handler(void)
#else
#error "not supported yet!"
#endif
{
    /\* do nothing. */
}

**Comment by grissiom** [comment]
Could you please send it in patch format? Or a pull request is better.

By the way, the STM32F4xx_Libraries and driver have a copy for both examples and realtouch. Is there a way to union them? So we don't have to repeat ourselves. ;)

**Comment by prife** [comment]
1, Okay, the patch:

```
diff --git a/software/examples/drivers/stm32f4xx_it.c b/software/examples/drivers/stm32f4xx_it.c
index cae0db7..d007914 100644
--- a/software/examples/drivers/stm32f4xx_it.c
+++ b/software/examples/drivers/stm32f4xx_it.c
@@ -198,7 +198,14 @@ EXTI6: KEY_RIGHT PF9
 */
 extern void key_handler(void);

+#if defined(__CC_ARM)
 __weak void key_handler(void)
+#elif defined(__GNUC__)
+void  key_handler(void) __attribute__ ((weak));
+void key_handler(void)
+#else
+#error "not supported yet!"
+#endif
 {
     /* do nothing. */
 }
```
1. 我也这么认为...

**Comment by BernardXiong** [comment]
尝试下，在scons中做个函数，能够把一些远程指向的文件都复制到本地来，这样对于以后维护就方便多了。

**Comment by grissiom** [comment]
@aozima example 和 realtouch 里的 driver 和标准库差别不大，哪个是最新的？如果统一的话用哪个好？

**Comment by aozima** [comment]
空间并不是问题，再次链接到外面造成关系更加复杂。
现在RT-Thread主目录不在里面，对很多收到板子的同学来说都是不小的麻烦。

**Comment by grissiom** [comment]
driver 和标准库呢？嘿嘿嘿……

**Comment by aozima** [comment]
用空间换方便吧，毕竟不太熟的人占大部分，等到RT-Thread和RT-GUI稳定了，就copy一份过来。

**Comment by BernardXiong** [comment]
做个工具自动更新外链的代码吧，这样以后发布也方便些，否则代码统一的事情也愁死人

2012/7/25 aozima <
reply@reply.github.com
