### ISSUE TITLE
mkfs test with "-O2" compiled.

### ISSUE THREAD

**Issue by BernardXiong** [RT-Thread/realboard-stm32f4#4]
Please use SPI flash to do a mkfs() test. Some body reports that system will panic when compile it with "-O2" or "-O3" parameter.

**Comment by grissiom** [comment]
What is the tool chain? MDK or GCC?

**Comment by prife** [comment]
mdk 4.50
-O2

finsh>>mkfs("elm", "flash0")
psr: 0x21000000
 pc: 0x0800e03c
 lr: 0x0800ded5
r12: 0x00000000
r03: 0x4e204f4e
r02: 0x0000000f
r01: 0x0800e084
r00: 0x20002e4f
hard fault on thread: tshell
 thread  pri  status      sp     stack size max used   left tick  error

---

tshell   0x14 ready   0x00000070 0x00000800 0x00000218 0x00000009 000
tidle    0x1f ready   0x00000040 0x00000400 0x00000050 0x00000007 000

I am tracing this issue.

2012/7/30 Grissiom.GuRui <
reply@reply.github.com

> What is the tool chain? MDK or GCC?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/RT-Thread/realtouch-stm32f4/issues/4#issuecomment-7366607

## 

把有限的时间投入到无限的学习中去

**Comment by prife** [comment]
2012/7/30 prife goprife@gmail.com

> mdk 4.50
> -O2
> 
> finsh>>mkfs("elm", "flash0")
> psr: 0x21000000
>  pc: 0x0800e03c
>  lr: 0x0800ded5
> r12: 0x00000000
> r03: 0x4e204f4e
> r02: 0x0000000f
> r01: 0x0800e084
> r00: 0x20002e4f
> hard fault on thread: tshell
>  thread  pri  status      sp     stack size max used   left tick  error
> 
> ---
> 
> tshell   0x14 ready   0x00000070 0x00000800 0x00000218 0x00000009 000
> tidle    0x1f ready   0x00000040 0x00000400 0x00000050 0x00000007 000
> 
> I am tracing this issue.

the bug is also a non-align issue..

ff.c 3178行

```
mem_cpy(tbl+BS_VolLab, "NO NAME    " "FAT     ", 19); /* Volume label, FAT signature */
```

mem_cpy：

```
/* Copy memory to memory */
static
void mem_cpy (void* dst, const void* src, UINT cnt) {
    BYTE *d = (BYTE*)dst;
    const BYTE *s = (const BYTE*)src;

#if _WORD_ACCESS == 1
    while (cnt >= sizeof(int)) {
        *(int*)d = *(int*)s;
        d += sizeof(int); s += sizeof(int);
        cnt -= sizeof(int);
    }
#endif
    while (cnt--)
        *d++ = *s++;
}
```

if  _WORD_ACCESS is defined, then the mem_cpy  may cause crash when the pointer of ram is not aligned..

so we can substitute the mem_cpy with the memcry provided by libraries in toolchain,

```
               memcpy(tbl+BS_VolLab, "NO NAME    " "FAT     ", 19); /*Volume label, FAT signature */
```

then it will works very well.

> 2012/7/30 Grissiom.GuRui <
> reply@reply.github.com
> 
> 
> What is the tool chain? MDK or GCC?
> 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/RT-Thread/realtouch-stm32f4/issues/4#issuecomment-7366607
> 
> ## 
> 
> 把有限的时间投入到无限的学习中去

## 

把有限的时间投入到无限的学习中去

**Comment by prife** [comment]
Fixed：
http://code.google.com/p/rt-thread/source/detail?r=2239

2012/7/30 prife goprife@gmail.com

> 2012/7/30 prife goprife@gmail.com
> 
> > mdk 4.50
> > -O2
> > 
> > finsh>>mkfs("elm", "flash0")
> > psr: 0x21000000
> >  pc: 0x0800e03c
> >  lr: 0x0800ded5
> > r12: 0x00000000
> > r03: 0x4e204f4e
> > r02: 0x0000000f
> > r01: 0x0800e084
> > r00: 0x20002e4f
> > hard fault on thread: tshell
> >  thread  pri  status      sp     stack size max used   left tick  error
> > 
> > ---
> > 
> > tshell   0x14 ready   0x00000070 0x00000800 0x00000218 0x00000009 000
> > tidle    0x1f ready   0x00000040 0x00000400 0x00000050 0x00000007 000
> > 
> > I am tracing this issue.
> 
> the bug is also a non-align issue
> 
> ff.c 3178行
> mem_cpy(tbl+BS_VolLab, "NO NAME    " "FAT     ", 19); /\* Volume label,
> FAT signature */
> 
> mem_cpy：
> 
> /\* Copy memory to memory _/
> static
> void mem_cpy (void_ dst, const void\* src, UINT cnt) {
> BYTE _d = (BYTE_)dst;
>  const BYTE _s = (const BYTE_)src;
> 
> #if _WORD_ACCESS == 1
> while (cnt >= sizeof(int)) {
>  _(int_)d = _(int_)s;
> d += sizeof(int); s += sizeof(int);
> cnt -= sizeof(int);
>  }
> #endif
> while (cnt--)
> *d++ = *s++;
> }
> 
> if  _WORD_ACCESS is defined, then the mem_cpy  may cause crash when the
> pointer of ram is not aligned..
> 
> so we can substitute the mem_cpy with the memcry provided by libraries in
> toolchain,
> 
> ```
>            memcpy(tbl+BS_VolLab, "NO NAME    " "FAT     ", 19); /*
> ```
> 
> Volume label, FAT signature */
> 
> then it will works very well.
> 
> > 2012/7/30 Grissiom.GuRui <
> > reply@reply.github.com
> > 
> > 
> > What is the tool chain? MDK or GCC?
> > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > 
> > > https://github.com/RT-Thread/realtouch-stm32f4/issues/4#issuecomment-7366607
> > 
> > ## 
> > 
> > 把有限的时间投入到无限的学习中去
> 
> ## 
> 
> 把有限的时间投入到无限的学习中去

## 

把有限的时间投入到无限的学习中去

**Comment by grissiom** [comment]
Close this issue since it have been fixed already.
